#!/bin/bash
#SBATCH -N 1
#SBATCH -p gpu_short
#SBATCH -t 0-01:00:00
#SBATCH -J exp2c
#SBATCH -n 2
#SBATCH -o exp2c

echo start of job

module load python
module load mkl
module load cuda/8.0.44

. ~/virtual_env_machine/bin/activate

cd ~/machine

time srun --multi-prog -o ~/output_run-%t-0 job_config/exp2c.conf 0
time srun --multi-prog -o ~/output_run-%t-1 job_config/exp2c.conf 1
time srun --multi-prog -o ~/output_run-%t-2 job_config/exp2c.conf 2

deactivate

echo end of job
